version: 2.1

# Define reusable commands
commands:
  terraform_init:
    description: "Initialize Terraform"
    steps:
      - run:
          name: "Terraform Init"
          command: |
            terraform init \
              -backend-config="key=ephemeral-environments/pr-${CIRCLE_PULL_REQUEST##*/}/terraform.tfstate"
  terraform_plan:
    description: "Run Terraform Plan"
    steps:
      - run:
          name: "Terraform Plan"
          command: terraform plan -var="pr_number=${CIRCLE_PULL_REQUEST##*/}"

  terraform_apply:
    description: "Run Terraform Apply"
    steps:
      - run:
          name: "Terraform Apply"
          command: terraform apply -auto-approve -var="pr_number=${CIRCLE_PULL_REQUEST##*/}"

  terraform_destroy:
    description: "Run Terraform Destroy"
    steps:
      - run:
          name: "Terraform Destroy"
          command: terraform destroy -auto-approve -var="pr_number=${CIRCLE_PULL_REQUEST##*/}"

# Define jobs
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - terraform_init
      - terraform_plan

  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - terraform_init
      - terraform_apply

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - terraform_init
      - terraform_destroy

# Define workflows
workflows:
  version: 2
  pr_workflow:
    jobs:
      - plan:
          context: aws-creds # Use a context for AWS credentials
          filters:
            branches:
              ignore: main # Only run on PRs, not on main branch
      - hold_for_approval:
          type: approval
          requires:
            - plan
          filters:
            branches:
              ignore: main # Only run on PRs, not on main branch
      - apply:
          requires:
            - hold_for_approval
          context: aws-creds
          filters:
            branches:
              ignore: main # Only run on PRs, not on main branch
  destroy_workflow:
    jobs:
      - destroy:
          context: aws-creds
          filters:
            branches:
              only: main # Only run when merging to main