version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project

jobs:
  setup-environment:
    executor: terraform-executor
    parameters:
      is_backend:
        type: boolean
      is_frontend:
        type: boolean
    steps:
      - checkout

      - run:
          name: Extract PR Number
          command: |
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | grep -oE '[0-9]+$')
              echo "PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
              echo "This is a PR: PR Number is $PR_NUMBER"
            else
              echo "Not a PR, skipping deployment."
              circleci step halt
            fi

      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

      - run:
          name: Configure AWS Credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: |
            terraform plan -var-file=terraform.ephemeral.tfvars \
              -var="pr_number=$PR_NUMBER" \
              -var="is_backend=<< parameters.is_backend >>" \
              -var="is_frontend=<< parameters.is_frontend >>"

      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve -var-file=terraform.ephemeral.tfvars \
              -var="pr_number=$PR_NUMBER" \
              -var="is_backend=<< parameters.is_backend >>" \
              -var="is_frontend=<< parameters.is_frontend >>"

  destroy-environment:
    executor: terraform-executor
    steps:
      - checkout

      - run:
          name: Extract PR Number
          command: |
            if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
              PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | grep -oE '[0-9]+$')
              echo "PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
              echo "Destroying environment for PR $PR_NUMBER"
            else
              echo "Not a PR, skipping destroy."
              circleci step halt
            fi

      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Destroy Terraform Resources
          command: |
            terraform destroy -auto-approve -var-file=terraform.ephemeral.tfvars \
              -var="pr_number=$PR_NUMBER"

workflows:
  version: 2
  workflow-pr-open:
    jobs:
      - setup-environment:
          filters:
            branches:
              only: /.*/  # Runs on all PR branches
          is_backend: true
          is_frontend: false

  workflow-pr-close:
    jobs:
      - destroy-environment:
          filters:
            branches:
              ignore: /.*/  # Runs when PR branch is deleted
