version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/project

jobs:
  setup-environment:
    executor: terraform-executor
    parameters:
      is_backend:
        type: boolean
      is_frontend:
        type: boolean
    steps:
      - checkout

      - run:
          name: Extract PR Number
          command: |
            echo "Extracting PR number..."
            PR_NUMBER=$(echo "${CIRCLE_PULL_REQUEST}" | sed 's|.*/pull/||')
            echo "PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
            echo "PR Number is $PR_NUMBER"

      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y unzip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Configure AWS Credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: |
            terraform plan -var-file=terraform.ephemeral.tfvars \
              -var="pr_number=$PR_NUMBER" \
              -var="is_backend=<< parameters.is_backend >>" \
              -var="is_frontend=<< parameters.is_frontend >>"

      - run:
          name: Terraform Apply
          command: |
            terraform apply -auto-approve -var-file=terraform.ephemeral.tfvars \
              -var="pr_number=$PR_NUMBER" \
              -var="is_backend=<< parameters.is_backend >>" \
              -var="is_frontend=<< parameters.is_frontend >>"

  destroy-environment:
    executor: terraform-executor
    steps:
      - checkout

      - run:
          name: Extract PR Number
          command: |
            PR_NUMBER=$(echo "${CIRCLE_PULL_REQUEST}" | sed 's|.*/pull/||')
            echo "PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
            echo "PR Number is $PR_NUMBER"

      - run:
          name: Configure AWS Credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Destroy Terraform Resources
          command: |
            terraform destroy -auto-approve -var-file=terraform.ephemeral.tfvars \
              -var="pr_number=$PR_NUMBER"

workflows:
  version: 2
  pr-deployment:
    jobs:
      - setup-environment:
          context: AWS
          filters:
            branches:
              only: main
          is_backend: true
          is_frontend: false

      - destroy-environment:
          requires:
            - setup-environment
          context: AWS
          filters:
            branches:
              ignore: main