version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

commands:
  terraform_init:
    description: "Initialize Terraform"
    steps:
      - run:
          name: "Terraform Init"
          command: |
            terraform init \
              -backend-config="key=ephemeral-environments/pr-${CIRCLE_PULL_REQUEST##*/}/terraform.tfstate"

  terraform_plan:
    description: "Run Terraform Plan"
    steps:
      - run:
          name: "Terraform Plan"
          command: |
            terraform plan \
              -var-file="terraform.ephemeral.tfvars" \
              -var="pr_number=${CIRCLE_PULL_REQUEST##*/}" \
              -out=tfplan

  terraform_apply:
    description: "Run Terraform Apply"
    steps:
      - run:
          name: "Terraform Apply"
          command: |
            terraform apply -auto-approve tfplan

  terraform_destroy:
    description: "Run Terraform Destroy"
    steps:
      - run:
          name: "Terraform Destroy"
          command: |
            terraform destroy \
              -auto-approve \
              -var-file="terraform.ephemeral.tfvars" \
              -var="pr_number=${CIRCLE_PULL_REQUEST##*/}"

jobs:
  plan:
    docker:
      - image: hashicorp/terraform:1.7
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - terraform_init
      - terraform_plan
      - persist_to_workspace:
          root: .
          paths:
            - .terraform
            - tfplan
            - "*.tf"
            - "*.tfvars"

  apply:
    docker:
      - image: hashicorp/terraform:1.7
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - attach_workspace:
          at: .
      - terraform_apply

  cleanup:
    docker:
      - image: hashicorp/terraform:1.7
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - terraform_init
      - terraform_destroy

workflows:
  version: 2
  terraform_pr:
    jobs:
      - plan:
          context: aws-creds
          filters:
            branches:
              ignore: main
            
      - hold_apply:
          type: approval
          requires:
            - plan
          filters:
            branches:
              ignore: main
            
      - apply:
          requires:
            - hold_apply
          context: aws-creds
          filters:
            branches:
              ignore: main

      - cleanup:
          requires:
            - apply
          context: aws-creds
          filters:
            branches:
              ignore: main